#!/bin/bash


if (whiptail --title "Monter ou Démonter ?" --yesno "Voulez vous monter les disques ou les démonter ?" 10 60 --yes-button "Monter" --no-button "Démonter") then
	mount /dev/data1/Vol1 /mnt/data1
	echo "data1/Vol1 is mounted"
else
	umount /dev/data1/Vol1 /mnt/data1
	echo "data1/Vol1 is unmounted"
fi

echo "nous vous laissons quelques secondes afins de lire les résultats de l'opération"
sleep 10

if (whiptail --title "Lancer une autre commande" --yesno "Voulez vous lancer une autre commande ?" --yes-button "oui" --no-button "non"  10 60) then
	bash ~/Bureau/projectLinuxMR
else
	echo "Au revoir"
fi