#!/bin/bash
docker exec -d phpmyadmin_db_1 mysqladmin -u root -p1234osradar create project
cat backup.sql | docker exec -i phpmyadmin_db_1 /usr/bin/mysql -u root --password=1234osradar project

echo "nous vous laissons quelques secondes afins de lire les résultats de l'opération"
sleep 10

if (whiptail --title "Lancer une autre commande" --yesno "Voulez vous lancer une autre commande ?" --yes-button "oui" --no-button "non"  10 60) then
        bash ~/Bureau/projectLinuxMR
else
        echo "Au revoir"
fis